import { PrismaClient } from '@prisma/client';

const NATIONALITIES = [
  { name_en: 'Afghan', name_id: 'Afghanistan', slug: 'afghan' },
  { name_en: 'Albanian', name_id: 'Albania', slug: 'albanian' },
  { name_en: 'Algerian', name_id: 'Aljazair', slug: 'algerian' },
  { name_en: 'American', name_id: 'Amerika', slug: 'american' },
  { name_en: 'Andorran', name_id: 'Andorra', slug: 'andorran' },
  { name_en: 'Angolan', name_id: 'Angola', slug: 'angolan' },
  { name_en: 'Argentine', name_id: 'Argentina', slug: 'argentine' },
  { name_en: 'Armenian', name_id: 'Armenia', slug: 'armenian' },
  { name_en: 'Australian', name_id: 'Australia', slug: 'australian' },
  { name_en: 'Austrian', name_id: 'Austria', slug: 'austrian' },
  { name_en: 'Azerbaijani', name_id: 'Azerbaijan', slug: 'azerbaijani' },
  { name_en: 'Bahamian', name_id: 'Bahama', slug: 'bahamian' },
  { name_en: 'Bahraini', name_id: 'Bahrain', slug: 'bahraini' },
  { name_en: 'Bangladeshi', name_id: 'Bangladesh', slug: 'bangladeshi' },
  { name_en: 'Barbadian', name_id: 'Barbados', slug: 'barbadian' },
  { name_en: 'Belarusian', name_id: 'Belarus', slug: 'belarusian' },
  { name_en: 'Belgian', name_id: 'Belgia', slug: 'belgian' },
  { name_en: 'Belizean', name_id: 'Belize', slug: 'belizean' },
  { name_en: 'Beninese', name_id: 'Benin', slug: 'beninese' },
  { name_en: 'Bhutanese', name_id: 'Bhutan', slug: 'bhutanese' },
  { name_en: 'Bolivian', name_id: 'Bolivia', slug: 'bolivian' },
  { name_en: 'Bosnian', name_id: 'Bosnia', slug: 'bosnian' },
  { name_en: 'Botswanan', name_id: 'Botswana', slug: 'botswanan' },
  { name_en: 'Brazilian', name_id: 'Brazil', slug: 'brazilian' },
  { name_en: 'British', name_id: 'Britania', slug: 'british' },
  { name_en: 'Bruneian', name_id: 'Brunei', slug: 'bruneian' },
  { name_en: 'Bulgarian', name_id: 'Bulgaria', slug: 'bulgarian' },
  { name_en: 'Burkinabe', name_id: 'Burkina Faso', slug: 'burkinabe' },
  { name_en: 'Burmese', name_id: 'Myanmar', slug: 'burmese' },
  { name_en: 'Burundian', name_id: 'Burundi', slug: 'burundian' },
  { name_en: 'Cambodian', name_id: 'Kamboja', slug: 'cambodian' },
  { name_en: 'Cameroonian', name_id: 'Kamerun', slug: 'cameroonian' },
  { name_en: 'Canadian', name_id: 'Kanada', slug: 'canadian' },
  { name_en: 'Cape Verdean', name_id: 'Tanjung Verde', slug: 'cape-verdean' },
  {
    name_en: 'Central African',
    name_id: 'Afrika Tengah',
    slug: 'central-african',
  },
  { name_en: 'Chadian', name_id: 'Chad', slug: 'chadian' },
  { name_en: 'Chilean', name_id: 'Chili', slug: 'chilean' },
  { name_en: 'Chinese', name_id: 'Tiongkok', slug: 'chinese' },
  { name_en: 'Colombian', name_id: 'Kolombia', slug: 'colombian' },
  { name_en: 'Comoran', name_id: 'Komoro', slug: 'comoran' },
  { name_en: 'Congolese', name_id: 'Kongo', slug: 'congolese' },
  { name_en: 'Costa Rican', name_id: 'Kosta Rika', slug: 'costa-rica' },
  { name_en: 'Croatian', name_id: 'Kroasia', slug: 'croatian' },
  { name_en: 'Cuban', name_id: 'Kuba', slug: 'cuban' },
  { name_en: 'Cypriot', name_id: 'Siprus', slug: 'cypriot' },
  { name_en: 'Czech', name_id: 'Ceko', slug: 'czech' },
  { name_en: 'Danish', name_id: 'Denmark', slug: 'danish' },
  { name_en: 'Djiboutian', name_id: 'Djibouti', slug: 'djiboutian' },
  { name_en: 'Dominican', name_id: 'Dominika', slug: 'dominican' },
  { name_en: 'Dutch', name_id: 'Belanda', slug: 'dutch' },
  { name_en: 'East Timorese', name_id: 'Timor Leste', slug: 'east-timorese' },
  { name_en: 'Ecuadorian', name_id: 'Ekuador', slug: 'ecuadorian' },
  { name_en: 'Egyptian', name_id: 'Mesir', slug: 'egyptian' },
  { name_en: 'Salvadoran', name_id: 'El Salvador', slug: 'salvadoran' },
  {
    name_en: 'Equatorial Guinean',
    name_id: 'Guinea Khatulistiwa',
    slug: 'equatorial',
  },
  { name_en: 'Eritrean', name_id: 'Eritrea', slug: 'eritrean' },
  { name_en: 'Estonian', name_id: 'Estonia', slug: 'estonian' },
  { name_en: 'Ethiopian', name_id: 'Etiopia', slug: 'ethiopian' },
  { name_en: 'Fijian', name_id: 'Fiji', slug: 'fijian' },
  { name_en: 'Finnish', name_id: 'Finlandia', slug: 'finnish' },
  { name_en: 'French', name_id: 'Prancis', slug: 'french' },
  { name_en: 'Gabonese', name_id: 'Gabon', slug: 'gabonese' },
  { name_en: 'Gambian', name_id: 'Gambia', slug: 'gambian' },
  { name_en: 'Georgian', name_id: 'Georgia', slug: 'georgian' },
  { name_en: 'German', name_id: 'Jerman', slug: 'german' },
  { name_en: 'Ghanaian', name_id: 'Ghana', slug: 'ghanaian' },
  { name_en: 'Greek', name_id: 'Yunani', slug: 'greek' },
  { name_en: 'Grenadian', name_id: 'Grenada', slug: 'grenadian' },
  { name_en: 'Guatemalan', name_id: 'Guatemala', slug: 'guatemalan' },
  { name_en: 'Guinean', name_id: 'Guinea', slug: 'guinean' },
  { name_en: 'Guinean-Bissau', name_id: 'Guinea-Bissau', slug: 'guinean-bissau' },
  { name_en: 'Guyanese', name_id: 'Guyana', slug: 'guyanese' },
  { name_en: 'Haitian', name_id: 'Haiti', slug: 'haitian' },
  { name_en: 'Honduran', name_id: 'Honduras', slug: 'honduran' },
  { name_en: 'Hungarian', name_id: 'Hongaria', slug: 'hungarian' },
  { name_en: 'Icelandic', name_id: 'Islandia', slug: 'icelandic' },
  { name_en: 'Indian', name_id: 'India', slug: 'indian' },
  { name_en: 'Indonesian', name_id: 'Indonesia', slug: 'indonesian' },
  { name_en: 'Iranian', name_id: 'Iran', slug: 'iranian' },
  { name_en: 'Iraqi', name_id: 'Irak', slug: 'iraqi' },
  { name_en: 'Irish', name_id: 'Irlandia', slug: 'irish' },
  { name_en: 'Italian', name_id: 'Italia', slug: 'italian' },
  { name_en: 'Ivorian', name_id: 'Pantai Gading', slug: 'ivorian' },
  { name_en: 'Jamaican', name_id: 'Jamaika', slug: 'jamaican' },
  { name_en: 'Japanese', name_id: 'Jepang', slug: 'japanese' },
  { name_en: 'Jordanian', name_id: 'Yordania', slug: 'jordanian' },
  { name_en: 'Kazakh', name_id: 'Kazakhstan', slug: 'kazakh' },
  { name_en: 'Kenyan', name_id: 'Kenya', slug: 'kenyan' },
  { name_en: 'Kiribati', name_id: 'Kiribati', slug: 'kiribati' },
  { name_en: 'Korean', name_id: 'Korea', slug: 'korean' },
  { name_en: 'Kosovar', name_id: 'Kosovo', slug: 'kosovar' },
  { name_en: 'Kuwaiti', name_id: 'Kuwait', slug: 'kuwaiti' },
  { name_en: 'Kyrgyz', name_id: 'Kyrgyzstan', slug: 'kyrgyz' },
  { name_en: 'Laotian', name_id: 'Laos', slug: 'laotian' },
  { name_en: 'Latvian', name_id: 'Latvia', slug: 'latvian' },
  { name_en: 'Lebanese', name_id: 'Lebanon', slug: 'lebanese' },
  { name_en: 'Lesotho', name_id: 'Lesotho', slug: 'lesotho' },
  { name_en: 'Liberian', name_id: 'Liberia', slug: 'liberian' },
  { name_en: 'Libyan', name_id: 'Libya', slug: 'libyan' },
  { name_en: 'Liechtenstein', name_id: 'Liechtenstein', slug: 'liechtenstein' },
  { name_en: 'Lithuanian', name_id: 'Lituania', slug: 'lithuanian' },
  { name_en: 'Luxembourgish', name_id: 'Luksemburg', slug: 'luxembourgish' },
  { name_en: 'Malagasy', name_id: 'Madagaskar', slug: 'malagasy' },
  { name_en: 'Malawian', name_id: 'Malawi', slug: 'malawian' },
  { name_en: 'Malaysian', name_id: 'Malaysia', slug: 'malaysian' },
  { name_en: 'Maldivian', name_id: 'Maladewa', slug: 'maldivian' },
  { name_en: 'Malian', name_id: 'Mali', slug: 'malian' },
  { name_en: 'Maltese', name_id: 'Malta', slug: 'maltese' },
  {
    name_en: 'Marshallese',
    name_id: 'Kepulauan Marshall',
    slug: 'marshallese',
  },
  { name_en: 'Mauritanian', name_id: 'Mauritania', slug: 'mauritanian' },
  { name_en: 'Mauritian', name_id: 'Mauritius', slug: 'mauritian' },
  { name_en: 'Mexican', name_id: 'Meksiko', slug: 'mexican' },
  { name_en: 'Micronesian', name_id: 'Mikronesia', slug: 'micronesian' },
  { name_en: 'Moldovan', name_id: 'Moldova', slug: 'moldovan' },
  { name_en: 'Monacan', name_id: 'Monako', slug: 'monacan' },
  { name_en: 'Mongolian', name_id: 'Mongolia', slug: 'mongolian' },
  { name_en: 'Montenegrin', name_id: 'Montenegro', slug: 'montenegrin' },
  { name_en: 'Moroccan', name_id: 'Maroko', slug: 'moroccan' },
  { name_en: 'Mozambican', name_id: 'Mozambik', slug: 'mozambican' },
  { name_en: 'Namibian', name_id: 'Namibia', slug: 'namibian' },
  { name_en: 'Nauruan', name_id: 'Nauru', slug: 'nauruan' },
  { name_en: 'Nepalese', name_id: 'Nepal', slug: 'nepalese' },
  { name_en: 'New Zealander', name_id: 'Selandia Baru', slug: 'new-zealander' },
  { name_en: 'Nicaraguan', name_id: 'Nikaragua', slug: 'nicaraguan' },
  { name_en: 'Nigerien', name_id: 'Niger', slug: 'nigerien' },
  { name_en: 'Nigerian', name_id: 'Nigeria', slug: 'nigerian' },
  { name_en: 'Norwegian', name_id: 'Norwegia', slug: 'norwegian' },
  { name_en: 'Omani', name_id: 'Oman', slug: 'omani' },
  { name_en: 'Pakistani', name_id: 'Pakistan', slug: 'pakistani' },
  { name_en: 'Palauan', name_id: 'Palau', slug: 'palauan' },
  { name_en: 'Palestinian', name_id: 'Palestina', slug: 'palestinian' },
  { name_en: 'Panamanian', name_id: 'Panama', slug: 'panamanian' },
  { name_en: 'Papua New Guinean', name_id: 'Papua Nugini', slug: 'papua-new-guinean' },
  { name_en: 'Paraguayan', name_id: 'Paraguay', slug: 'paraguayan' },
  { name_en: 'Peruvian', name_id: 'Peru', slug: 'peruvian' },
  { name_en: 'Filipino', name_id: 'Filipina', slug: 'filipino' },
  { name_en: 'Polish', name_id: 'Polandia', slug: 'polish' },
  { name_en: 'Portuguese', name_id: 'Portugal', slug: 'portuguese' },
  { name_en: 'Qatari', name_id: 'Qatar', slug: 'qatari' },
  { name_en: 'Romanian', name_id: 'Rumania', slug: 'romanian' },
  { name_en: 'Russian', name_id: 'Rusia', slug: 'russian' },
  { name_en: 'Rwandan', name_id: 'Rwanda', slug: 'rwandan' },
  { name_en: 'Saint Lucian', name_id: 'Santa Lucia', slug: 'saint-lucian' },
  { name_en: 'Saint Vincentian', name_id: 'Saint Vincent', slug: 'saint-vincentian' },
  { name_en: 'Samoan', name_id: 'Samoa', slug: 'samoan' },
  { name_en: 'San Marinese', name_id: 'San Marino', slug: 'san-marinese' },
  { name_en: 'Sao Tomean', name_id: 'Sao Tome dan Principe', slug: 'sao-tomean' },
  { name_en: 'Saudi Arabian', name_id: 'Arab Saudi', slug: 'saudi-arabian' },
  { name_en: 'Senegalese', name_id: 'Senegal', slug: 'senegalese' },
  { name_en: 'Serbian', name_id: 'Serbia', slug: 'serbian' },
  { name_en: 'Seychellois', name_id: 'Seychelles', slug: 'seychellois' },
  { name_en: 'Sierra Leonean', name_id: 'Sierra Leone', slug: 'sierra-leonean' },
  { name_en: 'Singaporean', name_id: 'Singapura', slug: 'singaporean' },
  { name_en: 'Slovak', name_id: 'Slovakia', slug: 'slovak' },
  { name_en: 'Slovenian', name_id: 'Slovenia', slug: 'slovenian' },
  {
    name_en: 'Solomon Islander',
    name_id: 'Kepulauan Solomon',
    slug: 'solomon-islander',
  },
  { name_en: 'Somali', name_id: 'Somalia', slug: 'somali' },
  { name_en: 'South African', name_id: 'Afrika Selatan', slug: 'south-african' },
  { name_en: 'South Sudanese', name_id: 'Sudan Selatan', slug: 'south-sudanese' },
  { name_en: 'Spanish', name_id: 'Spanyol', slug: 'spanish' },
  { name_en: 'Sri Lankan', name_id: 'Sri Lanka', slug: 'sri-lanka' },
  { name_en: 'Sudanese', name_id: 'Sudan', slug: 'sudanese' },
  { name_en: 'Surinamese', name_id: 'Suriname', slug: 'surinamese' },
  { name_en: 'Swazi', name_id: 'Swaziland', slug: 'swazi' },
  { name_en: 'Swedish', name_id: 'Swedia', slug: 'swedish' },
  { name_en: 'Swiss', name_id: 'Swiss', slug: 'swiss' },
  { name_en: 'Syrian', name_id: 'Suriah', slug: 'syrian' },
  { name_en: 'Taiwanese', name_id: 'Taiwan', slug: 'taiwanese' },
  { name_en: 'Tajik', name_id: 'Tajikistan', slug: 'tajik' },
  { name_en: 'Tanzanian', name_id: 'Tanzania', slug: 'tanzanian' },
  { name_en: 'Thai', name_id: 'Thailand', slug: 'thai' },
  { name_en: 'Togolese', name_id: 'Togo', slug: 'togolese' },
  { name_en: 'Tongan', name_id: 'Tonga', slug: 'tongan' },
  {
    name_en: 'Trinidadian',
    name_id: 'Trinidad dan Tobago',
    slug: 'trinidadian',
  },
  { name_en: 'Tunisian', name_id: 'Tunisia', slug: 'tunisian' },
  { name_en: 'Turkish', name_id: 'Turki', slug: 'turkish' },
  { name_en: 'Turkmen', name_id: 'Turkmenistan', slug: 'turkmen' },
  { name_en: 'Tuvaluan', name_id: 'Tuvalu', slug: 'tuvaluan' },
  { name_en: 'Ugandan', name_id: 'Uganda', slug: 'tgandan' },
  { name_en: 'Ukrainian', name_id: 'Ukraina', slug: 'tkrainian' },
  { name_en: 'Emirati', name_id: 'Uni Emirat Arab', slug: 'emirati' },
  { name_en: 'Uruguayan', name_id: 'Uruguay', slug: 'uruguayan' },
  { name_en: 'Uzbek', name_id: 'Uzbekistan', slug: 'uzbek' },
  { name_en: 'Vanuatuan', name_id: 'Vanuatu', slug: 'vanuatuan' },
  { name_en: 'Venezuelan', name_id: 'Venezuela', slug: 'venezuelan' },
  { name_en: 'Vietnamese', name_id: 'Vietnam', slug: 'vietnamese' },
  { name_en: 'Yemeni', name_id: 'Yaman', slug: 'yemeni' },
  { name_en: 'Zambian', name_id: 'Zambia', slug: 'zambian' },
  { name_en: 'Zimbabwean', name_id: 'Zimbabwe', slug: 'zimbabwean' },
];

const PROFESSIONS = [
  { name_en: 'Accountant', name_id: 'Akuntan', slug: 'accountant' },
  { name_en: 'Actor', name_id: 'Aktor', slug: 'actor' },
  { name_en: 'Actress', name_id: 'Aktris', slug: 'actress' },
  { name_en: 'Architect', name_id: 'Arsitek', slug: 'architect' },
  { name_en: 'Artist', name_id: 'Seniman', slug: 'artist' },
  { name_en: 'Athlete', name_id: 'Atlet', slug: 'athlete' },
  { name_en: 'Author', name_id: 'Pengarang', slug: 'author' },
  { name_en: 'Baker', name_id: 'Tukang Roti', slug: 'baker' },
  { name_en: 'Banker', name_id: 'Bankir', slug: 'banker' },
  { name_en: 'Barber', name_id: 'Tukang Cukur', slug: 'barber' },
  { name_en: 'Bartender', name_id: 'Bartender', slug: 'bartender' },
  { name_en: 'Beautician', name_id: 'Ahli Kecantikan', slug: 'beautician' },
  { name_en: 'Biologist', name_id: 'Ahli Biologi', slug: 'biologist' },
  { name_en: 'Blacksmith', name_id: 'Pandai Besi', slug: 'blacksmith' },
  { name_en: 'Butcher', name_id: 'Tukang Daging', slug: 'butcher' },
  { name_en: 'Carpenter', name_id: 'Tukang Kayu', slug: 'carpenter' },
  { name_en: 'Cashier', name_id: 'Kasir', slug: 'cashier' },
  { name_en: 'Chef', name_id: 'Koki', slug: 'chef' },
  { name_en: 'Chemist', name_id: 'Ahli Kimia', slug: 'chemist' },
  { name_en: 'Clerk', name_id: 'Pegawai', slug: 'clerk' },
  { name_en: 'Coach', name_id: 'Pelatih', slug: 'coach' },
  { name_en: 'Comedian', name_id: 'Pelawak', slug: 'comedian' },
  { name_en: 'Composer', name_id: 'Komposer', slug: 'composer' },
  { name_en: 'Cook', name_id: 'Juru Masak', slug: 'cook' },
  { name_en: 'Dancer', name_id: 'Penari', slug: 'dancer' },
  { name_en: 'Dentist', name_id: 'Dokter Gigi', slug: 'dentist' },
  { name_en: 'Designer', name_id: 'Desainer', slug: 'designer' },
  { name_en: 'Doctor', name_id: 'Dokter', slug: 'doctor' },
  { name_en: 'Driver', name_id: 'Pengemudi', slug: 'driver' },
  { name_en: 'Economist', name_id: 'Ekonom', slug: 'economist' },
  { name_en: 'Electrician', name_id: 'Tukang Listrik', slug: 'electrician' },
  { name_en: 'Engineer', name_id: 'Insinyur', slug: 'engineer' },
  { name_en: 'Farmer', name_id: 'Petani', slug: 'farmer' },
  { name_en: 'Fashion Designer', name_id: 'Desainer Mode', slug: 'fashion-designe' },
  { name_en: 'Firefighter', name_id: 'Pemadam Kebakaran', slug: 'firefighter' },
  { name_en: 'Fisherman', name_id: 'Nelayan', slug: 'fisherman' },
  { name_en: 'Florist', name_id: 'Penjual Bunga', slug: 'florist' },
  { name_en: 'Gardener', name_id: 'Tukang Kebun', slug: 'gardener' },
  { name_en: 'Hairdresser', name_id: 'Penata Rambut', slug: 'hairdresser' },
  { name_en: 'Journalist', name_id: 'Jurnalis', slug: 'journalist' },
  { name_en: 'Judge', name_id: 'Hakim', slug: 'judge' },
  { name_en: 'Lawyer', name_id: 'Pengacara', slug: 'lawyer' },
  { name_en: 'Lecturer', name_id: 'Dosen', slug: 'lecturer' },
  { name_en: 'Librarian', name_id: 'Pustakawan', slug: 'librarian' },
  { name_en: 'Mechanic', name_id: 'Mekanik', slug: 'mechanic' },
  { name_en: 'Musician', name_id: 'Musisi', slug: 'musician' },
  { name_en: 'Nurse', name_id: 'Perawat', slug: 'nurse' },
  { name_en: 'Painter', name_id: 'Pelukis', slug: 'painter' },
  { name_en: 'Pharmacist', name_id: 'Apoteker', slug: 'pharmacist' },
  { name_en: 'Photographer', name_id: 'Fotografer', slug: 'photographer' },
  { name_en: 'Pilot', name_id: 'Pilot', slug: 'pilot' },
  { name_en: 'Plumber', name_id: 'Tukang Ledeng', slug: 'plumber' },
  { name_en: 'Police Officer', name_id: 'Polisi', slug: 'police-office' },
  { name_en: 'Politician', name_id: 'Politikus', slug: 'politician' },
  { name_en: 'Postman', name_id: 'Tukang Pos', slug: 'postman' },
  { name_en: 'Professor', name_id: 'Profesor', slug: 'professor' },
  { name_en: 'Programmer', name_id: 'Programer', slug: 'programmer' },
  { name_en: 'Receptionist', name_id: 'Resepsionis', slug: 'receptionist' },
  { name_en: 'Scientist', name_id: 'Ilmuwan', slug: 'scientist' },
  { name_en: 'Secretary', name_id: 'Sekretaris', slug: 'secretary' },
  { name_en: 'Singer', name_id: 'Penyanyi', slug: 'singer' },
  { name_en: 'Soldier', name_id: 'Tentara', slug: 'soldier' },
  { name_en: 'Surgeon', name_id: 'Ahli Bedah', slug: 'surgeon' },
  { name_en: 'Tailor', name_id: 'Penjahit', slug: 'tailor' },
  { name_en: 'Teacher', name_id: 'Guru', slug: 'teacher' },
  { name_en: 'Technician', name_id: 'Teknisi', slug: 'technician' },
  { name_en: 'Translator', name_id: 'Penerjemah', slug: 'translator' },
  { name_en: 'Veterinarian', name_id: 'Dokter Hewan', slug: 'veterinarian' },
  { name_en: 'Waiter', name_id: 'Pelayan Pria', slug: 'waiter' },
  { name_en: 'Waitress', name_id: 'Pelayan Wanita', slug: 'waitress' },
  { name_en: 'Writer', name_id: 'Penulis', slug: 'writer' },
];

const CATEGORIES = [
  { name_en: 'Motivational', name_id: 'Motivasi', slug: 'motivational' },
  { name_en: 'Inspirational', name_id: 'Inspirasi', slug: 'inspirational' },
  { name_en: 'Love', name_id: 'Cinta', slug: 'love' },
  { name_en: 'Friendship', name_id: 'Persahabatan', slug: 'friendship' },
  { name_en: 'Life', name_id: 'Kehidupan', slug: 'life' },
  { name_en: 'Happiness', name_id: 'Kebahagiaan', slug: 'happiness' },
  { name_en: 'Wisdom', name_id: 'Kebijaksanaan', slug: 'wisdom' },
  { name_en: 'Success', name_id: 'Kesuksesan', slug: 'success' },
  { name_en: 'Funny', name_id: 'Lucu', slug: 'funny' },
  { name_en: 'Philosophical', name_id: 'Filsafat', slug: 'philosophical' },
  { name_en: 'Positive', name_id: 'Positif', slug: 'positive' },
  { name_en: 'Sad', name_id: 'Sedih', slug: 'sad' },
  { name_en: 'Courage', name_id: 'Keberanian', slug: 'courage' },
  { name_en: 'Dream', name_id: 'Mimpi', slug: 'dream' },
  { name_en: 'Education', name_id: 'Pendidikan', slug: 'education' },
  { name_en: 'Family', name_id: 'Keluarga', slug: 'family' },
  { name_en: 'Health', name_id: 'Kesehatan', slug: 'health' },
  { name_en: 'Humor', name_id: 'Humor', slug: 'humor' },
  { name_en: 'Leadership', name_id: 'Kepemimpinan', slug: 'leadership' },
  { name_en: 'Patience', name_id: 'Kesabaran', slug: 'patience' },
  { name_en: 'Peace', name_id: 'Perdamaian', slug: 'peace' },
  { name_en: 'Spiritual', name_id: 'Spiritual', slug: 'spiritual' },
  { name_en: 'Strength', name_id: 'Kekuatan', slug: 'strength' },
  { name_en: 'Time', name_id: 'Waktu', slug: 'time' },
  { name_en: 'Travel', name_id: 'Perjalanan', slug: 'travel' },
  { name_en: 'Work', name_id: 'Kerja', slug: 'work' },
  { name_en: 'Art', name_id: 'Seni', slug: 'art' },
  { name_en: 'Nature', name_id: 'Alam', slug: 'nature' },
  { name_en: 'Freedom', name_id: 'Kebebasan', slug: 'freedom' },
  { name_en: 'Gratitude', name_id: 'Rasa Syukur', slug: 'gratitude' },
  { name_en: 'Forgiveness', name_id: 'Pengampunan', slug: 'forgiveness' },
  { name_en: 'Self-love', name_id: 'Cinta Diri', slug: 'self-love' },
  { name_en: 'Mindfulness', name_id: 'Kewaspadaan', slug: 'mindfulness' },
  { name_en: 'Adventure', name_id: 'Petualangan', slug: 'adventure' },
  { name_en: 'Hope', name_id: 'Harapan', slug: 'hope' },
  { name_en: 'Change', name_id: 'Perubahan', slug: 'change' },
  { name_en: 'Determination', name_id: 'Tekad', slug: 'determination' },
  { name_en: 'Resilience', name_id: 'Ketahanan', slug: 'resilience' },
  { name_en: 'Empathy', name_id: 'Empati', slug: 'empathy' },
  { name_en: 'Compassion', name_id: 'Belas Kasihan', slug: 'compassion' },
  { name_en: 'Kindness', name_id: 'Kebaikan', slug: 'kindness' },
  { name_en: 'Faith', name_id: 'Iman', slug: 'faith' },
];

const prisma = new PrismaClient();
async function main() {
  await prisma.nationality.createMany({
    data: NATIONALITIES,
  });

  await prisma.profession.createMany({
    data: PROFESSIONS,
  });

  await prisma.category.createMany({
    data: CATEGORIES,
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
