import { PrismaClient } from '@prisma/client';

const NATIONALITIES = [
  { name_eng: 'Afghan', name_ind: 'Afghanistan', slug: 'afghan' },
  { name_eng: 'Albanian', name_ind: 'Albania', slug: 'albanian' },
  { name_eng: 'Algerian', name_ind: 'Aljazair', slug: 'algerian' },
  { name_eng: 'American', name_ind: 'Amerika', slug: 'american' },
  { name_eng: 'Andorran', name_ind: 'Andorra', slug: 'andorran' },
  { name_eng: 'Angolan', name_ind: 'Angola', slug: 'angolan' },
  { name_eng: 'Argentine', name_ind: 'Argentina', slug: 'argentine' },
  { name_eng: 'Armenian', name_ind: 'Armenia', slug: 'armenian' },
  { name_eng: 'Australian', name_ind: 'Australia', slug: 'australian' },
  { name_eng: 'Austrian', name_ind: 'Austria', slug: 'austrian' },
  { name_eng: 'Azerbaijani', name_ind: 'Azerbaijan', slug: 'azerbaijani' },
  { name_eng: 'Bahamian', name_ind: 'Bahama', slug: 'bahamian' },
  { name_eng: 'Bahraini', name_ind: 'Bahrain', slug: 'bahraini' },
  { name_eng: 'Bangladeshi', name_ind: 'Bangladesh', slug: 'bangladeshi' },
  { name_eng: 'Barbadian', name_ind: 'Barbados', slug: 'barbadian' },
  { name_eng: 'Belarusian', name_ind: 'Belarus', slug: 'belarusian' },
  { name_eng: 'Belgian', name_ind: 'Belgia', slug: 'belgian' },
  { name_eng: 'Belizean', name_ind: 'Belize', slug: 'belizean' },
  { name_eng: 'Beninese', name_ind: 'Benin', slug: 'beninese' },
  { name_eng: 'Bhutanese', name_ind: 'Bhutan', slug: 'bhutanese' },
  { name_eng: 'Bolivian', name_ind: 'Bolivia', slug: 'bolivian' },
  { name_eng: 'Bosnian', name_ind: 'Bosnia', slug: 'bosnian' },
  { name_eng: 'Botswanan', name_ind: 'Botswana', slug: 'botswanan' },
  { name_eng: 'Brazilian', name_ind: 'Brazil', slug: 'brazilian' },
  { name_eng: 'British', name_ind: 'Britania', slug: 'british' },
  { name_eng: 'Bruneian', name_ind: 'Brunei', slug: 'bruneian' },
  { name_eng: 'Bulgarian', name_ind: 'Bulgaria', slug: 'bulgarian' },
  { name_eng: 'Burkinabe', name_ind: 'Burkina Faso', slug: 'burkinabe' },
  { name_eng: 'Burmese', name_ind: 'Myanmar', slug: 'burmese' },
  { name_eng: 'Burundian', name_ind: 'Burundi', slug: 'burundian' },
  { name_eng: 'Cambodian', name_ind: 'Kamboja', slug: 'cambodian' },
  { name_eng: 'Cameroonian', name_ind: 'Kamerun', slug: 'cameroonian' },
  { name_eng: 'Canadian', name_ind: 'Kanada', slug: 'canadian' },
  { name_eng: 'Cape Verdean', name_ind: 'Tanjung Verde', slug: 'cape-verdean' },
  {
    name_eng: 'Central African',
    name_ind: 'Afrika Tengah',
    slug: 'central-african',
  },
  { name_eng: 'Chadian', name_ind: 'Chad', slug: 'chadian' },
  { name_eng: 'Chilean', name_ind: 'Chili', slug: 'chilean' },
  { name_eng: 'Chinese', name_ind: 'Tiongkok', slug: 'chinese' },
  { name_eng: 'Colombian', name_ind: 'Kolombia', slug: 'colombian' },
  { name_eng: 'Comoran', name_ind: 'Komoro', slug: 'comoran' },
  { name_eng: 'Congolese', name_ind: 'Kongo', slug: 'congolese' },
  { name_eng: 'Costa Rican', name_ind: 'Kosta Rika', slug: 'costa-rica' },
  { name_eng: 'Croatian', name_ind: 'Kroasia', slug: 'croatian' },
  { name_eng: 'Cuban', name_ind: 'Kuba', slug: 'cuban' },
  { name_eng: 'Cypriot', name_ind: 'Siprus', slug: 'cypriot' },
  { name_eng: 'Czech', name_ind: 'Ceko', slug: 'czech' },
  { name_eng: 'Danish', name_ind: 'Denmark', slug: 'danish' },
  { name_eng: 'Djiboutian', name_ind: 'Djibouti', slug: 'djiboutian' },
  { name_eng: 'Dominican', name_ind: 'Dominika', slug: 'dominican' },
  { name_eng: 'Dutch', name_ind: 'Belanda', slug: 'dutch' },
  { name_eng: 'East Timorese', name_ind: 'Timor Leste', slug: 'east-timorese' },
  { name_eng: 'Ecuadorian', name_ind: 'Ekuador', slug: 'ecuadorian' },
  { name_eng: 'Egyptian', name_ind: 'Mesir', slug: 'egyptian' },
  { name_eng: 'Salvadoran', name_ind: 'El Salvador', slug: 'salvadoran' },
  {
    name_eng: 'Equatorial Guinean',
    name_ind: 'Guinea Khatulistiwa',
    slug: 'equatorial',
  },
  { name_eng: 'Eritrean', name_ind: 'Eritrea', slug: 'eritrean' },
  { name_eng: 'Estonian', name_ind: 'Estonia', slug: 'estonian' },
  { name_eng: 'Ethiopian', name_ind: 'Etiopia', slug: 'ethiopian' },
  { name_eng: 'Fijian', name_ind: 'Fiji', slug: 'fijian' },
  { name_eng: 'Finnish', name_ind: 'Finlandia', slug: 'finnish' },
  { name_eng: 'French', name_ind: 'Prancis', slug: 'french' },
  { name_eng: 'Gabonese', name_ind: 'Gabon', slug: 'gabonese' },
  { name_eng: 'Gambian', name_ind: 'Gambia', slug: 'gambian' },
  { name_eng: 'Georgian', name_ind: 'Georgia', slug: 'georgian' },
  { name_eng: 'German', name_ind: 'Jerman', slug: 'german' },
  { name_eng: 'Ghanaian', name_ind: 'Ghana', slug: 'ghanaian' },
  { name_eng: 'Greek', name_ind: 'Yunani', slug: 'greek' },
  { name_eng: 'Grenadian', name_ind: 'Grenada', slug: 'grenadian' },
  { name_eng: 'Guatemalan', name_ind: 'Guatemala', slug: 'guatemalan' },
  { name_eng: 'Guinean', name_ind: 'Guinea', slug: 'guinean' },
  {
    name_eng: 'Guinean-Bissau',
    name_ind: 'Guinea-Bissau',
    slug: 'guinean-bissau',
  },
  { name_eng: 'Guyanese', name_ind: 'Guyana', slug: 'guyanese' },
  { name_eng: 'Haitian', name_ind: 'Haiti', slug: 'haitian' },
  { name_eng: 'Honduran', name_ind: 'Honduras', slug: 'honduran' },
  { name_eng: 'Hungarian', name_ind: 'Hongaria', slug: 'hungarian' },
  { name_eng: 'Icelandic', name_ind: 'Islandia', slug: 'icelandic' },
  { name_eng: 'Indian', name_ind: 'India', slug: 'indian' },
  { name_eng: 'Indonesian', name_ind: 'Indonesia', slug: 'indonesian' },
  { name_eng: 'Iranian', name_ind: 'Iran', slug: 'iranian' },
  { name_eng: 'Iraqi', name_ind: 'Irak', slug: 'iraqi' },
  { name_eng: 'Irish', name_ind: 'Irlandia', slug: 'irish' },
  { name_eng: 'Italian', name_ind: 'Italia', slug: 'italian' },
  { name_eng: 'Ivorian', name_ind: 'Pantai Gading', slug: 'ivorian' },
  { name_eng: 'Jamaican', name_ind: 'Jamaika', slug: 'jamaican' },
  { name_eng: 'Japanese', name_ind: 'Jepang', slug: 'japanese' },
  { name_eng: 'Jordanian', name_ind: 'Yordania', slug: 'jordanian' },
  { name_eng: 'Kazakh', name_ind: 'Kazakhstan', slug: 'kazakh' },
  { name_eng: 'Kenyan', name_ind: 'Kenya', slug: 'kenyan' },
  { name_eng: 'Kiribati', name_ind: 'Kiribati', slug: 'kiribati' },
  { name_eng: 'Korean', name_ind: 'Korea', slug: 'korean' },
  { name_eng: 'Kosovar', name_ind: 'Kosovo', slug: 'kosovar' },
  { name_eng: 'Kuwaiti', name_ind: 'Kuwait', slug: 'kuwaiti' },
  { name_eng: 'Kyrgyz', name_ind: 'Kyrgyzstan', slug: 'kyrgyz' },
  { name_eng: 'Laotian', name_ind: 'Laos', slug: 'laotian' },
  { name_eng: 'Latvian', name_ind: 'Latvia', slug: 'latvian' },
  { name_eng: 'Lebanese', name_ind: 'Lebanon', slug: 'lebanese' },
  { name_eng: 'Lesotho', name_ind: 'Lesotho', slug: 'lesotho' },
  { name_eng: 'Liberian', name_ind: 'Liberia', slug: 'liberian' },
  { name_eng: 'Libyan', name_ind: 'Libya', slug: 'libyan' },
  {
    name_eng: 'Liechtenstein',
    name_ind: 'Liechtenstein',
    slug: 'liechtenstein',
  },
  { name_eng: 'Lithuanian', name_ind: 'Lituania', slug: 'lithuanian' },
  { name_eng: 'Luxembourgish', name_ind: 'Luksemburg', slug: 'luxembourgish' },
  { name_eng: 'Malagasy', name_ind: 'Madagaskar', slug: 'malagasy' },
  { name_eng: 'Malawian', name_ind: 'Malawi', slug: 'malawian' },
  { name_eng: 'Malaysian', name_ind: 'Malaysia', slug: 'malaysian' },
  { name_eng: 'Maldivian', name_ind: 'Maladewa', slug: 'maldivian' },
  { name_eng: 'Malian', name_ind: 'Mali', slug: 'malian' },
  { name_eng: 'Maltese', name_ind: 'Malta', slug: 'maltese' },
  {
    name_eng: 'Marshallese',
    name_ind: 'Kepulauan Marshall',
    slug: 'marshallese',
  },
  { name_eng: 'Mauritanian', name_ind: 'Mauritania', slug: 'mauritanian' },
  { name_eng: 'Mauritian', name_ind: 'Mauritius', slug: 'mauritian' },
  { name_eng: 'Mexican', name_ind: 'Meksiko', slug: 'mexican' },
  { name_eng: 'Micronesian', name_ind: 'Mikronesia', slug: 'micronesian' },
  { name_eng: 'Moldovan', name_ind: 'Moldova', slug: 'moldovan' },
  { name_eng: 'Monacan', name_ind: 'Monako', slug: 'monacan' },
  { name_eng: 'Mongolian', name_ind: 'Mongolia', slug: 'mongolian' },
  { name_eng: 'Montenegrin', name_ind: 'Montenegro', slug: 'montenegrin' },
  { name_eng: 'Moroccan', name_ind: 'Maroko', slug: 'moroccan' },
  { name_eng: 'Mozambican', name_ind: 'Mozambik', slug: 'mozambican' },
  { name_eng: 'Namibian', name_ind: 'Namibia', slug: 'namibian' },
  { name_eng: 'Nauruan', name_ind: 'Nauru', slug: 'nauruan' },
  { name_eng: 'Nepalese', name_ind: 'Nepal', slug: 'nepalese' },
  {
    name_eng: 'New Zealander',
    name_ind: 'Selandia Baru',
    slug: 'new-zealander',
  },
  { name_eng: 'Nicaraguan', name_ind: 'Nikaragua', slug: 'nicaraguan' },
  { name_eng: 'Nigerien', name_ind: 'Niger', slug: 'nigerien' },
  { name_eng: 'Nigerian', name_ind: 'Nigeria', slug: 'nigerian' },
  { name_eng: 'Norwegian', name_ind: 'Norwegia', slug: 'norwegian' },
  { name_eng: 'Omani', name_ind: 'Oman', slug: 'omani' },
  { name_eng: 'Pakistani', name_ind: 'Pakistan', slug: 'pakistani' },
  { name_eng: 'Palauan', name_ind: 'Palau', slug: 'palauan' },
  { name_eng: 'Palestinian', name_ind: 'Palestina', slug: 'palestinian' },
  { name_eng: 'Panamanian', name_ind: 'Panama', slug: 'panamanian' },
  {
    name_eng: 'Papua New Guinean',
    name_ind: 'Papua Nugini',
    slug: 'papua-new-guinean',
  },
  { name_eng: 'Paraguayan', name_ind: 'Paraguay', slug: 'paraguayan' },
  { name_eng: 'Peruvian', name_ind: 'Peru', slug: 'peruvian' },
  { name_eng: 'Filipino', name_ind: 'Filipina', slug: 'filipino' },
  { name_eng: 'Polish', name_ind: 'Polandia', slug: 'polish' },
  { name_eng: 'Portuguese', name_ind: 'Portugal', slug: 'portuguese' },
  { name_eng: 'Qatari', name_ind: 'Qatar', slug: 'qatari' },
  { name_eng: 'Romanian', name_ind: 'Rumania', slug: 'romanian' },
  { name_eng: 'Russian', name_ind: 'Rusia', slug: 'russian' },
  { name_eng: 'Rwandan', name_ind: 'Rwanda', slug: 'rwandan' },
  { name_eng: 'Saint Lucian', name_ind: 'Santa Lucia', slug: 'saint-lucian' },
  {
    name_eng: 'Saint Vincentian',
    name_ind: 'Saint Vincent',
    slug: 'saint-vincentian',
  },
  { name_eng: 'Samoan', name_ind: 'Samoa', slug: 'samoan' },
  { name_eng: 'San Marinese', name_ind: 'San Marino', slug: 'san-marinese' },
  {
    name_eng: 'Sao Tomean',
    name_ind: 'Sao Tome dan Principe',
    slug: 'sao-tomean',
  },
  { name_eng: 'Saudi Arabian', name_ind: 'Arab Saudi', slug: 'saudi-arabian' },
  { name_eng: 'Senegalese', name_ind: 'Senegal', slug: 'senegalese' },
  { name_eng: 'Serbian', name_ind: 'Serbia', slug: 'serbian' },
  { name_eng: 'Seychellois', name_ind: 'Seychelles', slug: 'seychellois' },
  {
    name_eng: 'Sierra Leonean',
    name_ind: 'Sierra Leone',
    slug: 'sierra-leonean',
  },
  { name_eng: 'Singaporean', name_ind: 'Singapura', slug: 'singaporean' },
  { name_eng: 'Slovak', name_ind: 'Slovakia', slug: 'slovak' },
  { name_eng: 'Slovenian', name_ind: 'Slovenia', slug: 'slovenian' },
  {
    name_eng: 'Solomon Islander',
    name_ind: 'Kepulauan Solomon',
    slug: 'solomon-islander',
  },
  { name_eng: 'Somali', name_ind: 'Somalia', slug: 'somali' },
  {
    name_eng: 'South African',
    name_ind: 'Afrika Selatan',
    slug: 'south-african',
  },
  {
    name_eng: 'South Sudanese',
    name_ind: 'Sudan Selatan',
    slug: 'south-sudanese',
  },
  { name_eng: 'Spanish', name_ind: 'Spanyol', slug: 'spanish' },
  { name_eng: 'Sri Lankan', name_ind: 'Sri Lanka', slug: 'sri-lanka' },
  { name_eng: 'Sudanese', name_ind: 'Sudan', slug: 'sudanese' },
  { name_eng: 'Surinamese', name_ind: 'Suriname', slug: 'surinamese' },
  { name_eng: 'Swazi', name_ind: 'Swaziland', slug: 'swazi' },
  { name_eng: 'Swedish', name_ind: 'Swedia', slug: 'swedish' },
  { name_eng: 'Swiss', name_ind: 'Swiss', slug: 'swiss' },
  { name_eng: 'Syrian', name_ind: 'Suriah', slug: 'syrian' },
  { name_eng: 'Taiwanese', name_ind: 'Taiwan', slug: 'taiwanese' },
  { name_eng: 'Tajik', name_ind: 'Tajikistan', slug: 'tajik' },
  { name_eng: 'Tanzanian', name_ind: 'Tanzania', slug: 'tanzanian' },
  { name_eng: 'Thai', name_ind: 'Thailand', slug: 'thai' },
  { name_eng: 'Togolese', name_ind: 'Togo', slug: 'togolese' },
  { name_eng: 'Tongan', name_ind: 'Tonga', slug: 'tongan' },
  {
    name_eng: 'Trinidadian',
    name_ind: 'Trinidad dan Tobago',
    slug: 'trinidadian',
  },
  { name_eng: 'Tunisian', name_ind: 'Tunisia', slug: 'tunisian' },
  { name_eng: 'Turkish', name_ind: 'Turki', slug: 'turkish' },
  { name_eng: 'Turkmen', name_ind: 'Turkmenistan', slug: 'turkmen' },
  { name_eng: 'Tuvaluan', name_ind: 'Tuvalu', slug: 'tuvaluan' },
  { name_eng: 'Ugandan', name_ind: 'Uganda', slug: 'tgandan' },
  { name_eng: 'Ukrainian', name_ind: 'Ukraina', slug: 'tkrainian' },
  { name_eng: 'Emirati', name_ind: 'Uni Emirat Arab', slug: 'emirati' },
  { name_eng: 'Uruguayan', name_ind: 'Uruguay', slug: 'uruguayan' },
  { name_eng: 'Uzbek', name_ind: 'Uzbekistan', slug: 'uzbek' },
  { name_eng: 'Vanuatuan', name_ind: 'Vanuatu', slug: 'vanuatuan' },
  { name_eng: 'Venezuelan', name_ind: 'Venezuela', slug: 'venezuelan' },
  { name_eng: 'Vietnamese', name_ind: 'Vietnam', slug: 'vietnamese' },
  { name_eng: 'Yemeni', name_ind: 'Yaman', slug: 'yemeni' },
  { name_eng: 'Zambian', name_ind: 'Zambia', slug: 'zambian' },
  { name_eng: 'Zimbabwean', name_ind: 'Zimbabwe', slug: 'zimbabwean' },
];

const PROFESSIONS = [
  { name_eng: 'Accountant', name_ind: 'Akuntan', slug: 'accountant' },
  { name_eng: 'Actor', name_ind: 'Aktor', slug: 'actor' },
  { name_eng: 'Actress', name_ind: 'Aktris', slug: 'actress' },
  { name_eng: 'Architect', name_ind: 'Arsitek', slug: 'architect' },
  { name_eng: 'Artist', name_ind: 'Seniman', slug: 'artist' },
  { name_eng: 'Athlete', name_ind: 'Atlet', slug: 'athlete' },
  { name_eng: 'Author', name_ind: 'Pengarang', slug: 'author' },
  { name_eng: 'Baker', name_ind: 'Tukang Roti', slug: 'baker' },
  { name_eng: 'Banker', name_ind: 'Bankir', slug: 'banker' },
  { name_eng: 'Barber', name_ind: 'Tukang Cukur', slug: 'barber' },
  { name_eng: 'Bartender', name_ind: 'Bartender', slug: 'bartender' },
  { name_eng: 'Beautician', name_ind: 'Ahli Kecantikan', slug: 'beautician' },
  { name_eng: 'Biologist', name_ind: 'Ahli Biologi', slug: 'biologist' },
  { name_eng: 'Blacksmith', name_ind: 'Pandai Besi', slug: 'blacksmith' },
  { name_eng: 'Butcher', name_ind: 'Tukang Daging', slug: 'butcher' },
  { name_eng: 'Carpenter', name_ind: 'Tukang Kayu', slug: 'carpenter' },
  { name_eng: 'Cashier', name_ind: 'Kasir', slug: 'cashier' },
  { name_eng: 'Chef', name_ind: 'Koki', slug: 'chef' },
  { name_eng: 'Chemist', name_ind: 'Ahli Kimia', slug: 'chemist' },
  { name_eng: 'Clerk', name_ind: 'Pegawai', slug: 'clerk' },
  { name_eng: 'Coach', name_ind: 'Pelatih', slug: 'coach' },
  { name_eng: 'Comedian', name_ind: 'Pelawak', slug: 'comedian' },
  { name_eng: 'Composer', name_ind: 'Komposer', slug: 'composer' },
  { name_eng: 'Cook', name_ind: 'Juru Masak', slug: 'cook' },
  { name_eng: 'Dancer', name_ind: 'Penari', slug: 'dancer' },
  { name_eng: 'Dentist', name_ind: 'Dokter Gigi', slug: 'dentist' },
  { name_eng: 'Designer', name_ind: 'Desainer', slug: 'designer' },
  { name_eng: 'Doctor', name_ind: 'Dokter', slug: 'doctor' },
  { name_eng: 'Driver', name_ind: 'Pengemudi', slug: 'driver' },
  { name_eng: 'Economist', name_ind: 'Ekonom', slug: 'economist' },
  { name_eng: 'Electrician', name_ind: 'Tukang Listrik', slug: 'electrician' },
  { name_eng: 'Engineer', name_ind: 'Insinyur', slug: 'engineer' },
  { name_eng: 'Farmer', name_ind: 'Petani', slug: 'farmer' },
  {
    name_eng: 'Fashion Designer',
    name_ind: 'Desainer Mode',
    slug: 'fashion-designe',
  },
  {
    name_eng: 'Firefighter',
    name_ind: 'Pemadam Kebakaran',
    slug: 'firefighter',
  },
  { name_eng: 'Fisherman', name_ind: 'Nelayan', slug: 'fisherman' },
  { name_eng: 'Florist', name_ind: 'Penjual Bunga', slug: 'florist' },
  { name_eng: 'Gardener', name_ind: 'Tukang Kebun', slug: 'gardener' },
  { name_eng: 'Hairdresser', name_ind: 'Penata Rambut', slug: 'hairdresser' },
  { name_eng: 'Journalist', name_ind: 'Jurnalis', slug: 'journalist' },
  { name_eng: 'Judge', name_ind: 'Hakim', slug: 'judge' },
  { name_eng: 'Lawyer', name_ind: 'Pengacara', slug: 'lawyer' },
  { name_eng: 'Lecturer', name_ind: 'Dosen', slug: 'lecturer' },
  { name_eng: 'Librarian', name_ind: 'Pustakawan', slug: 'librarian' },
  { name_eng: 'Mechanic', name_ind: 'Mekanik', slug: 'mechanic' },
  { name_eng: 'Musician', name_ind: 'Musisi', slug: 'musician' },
  { name_eng: 'Nurse', name_ind: 'Perawat', slug: 'nurse' },
  { name_eng: 'Painter', name_ind: 'Pelukis', slug: 'painter' },
  { name_eng: 'Pharmacist', name_ind: 'Apoteker', slug: 'pharmacist' },
  { name_eng: 'Photographer', name_ind: 'Fotografer', slug: 'photographer' },
  { name_eng: 'Pilot', name_ind: 'Pilot', slug: 'pilot' },
  { name_eng: 'Plumber', name_ind: 'Tukang Ledeng', slug: 'plumber' },
  { name_eng: 'Police Officer', name_ind: 'Polisi', slug: 'police-office' },
  { name_eng: 'Politician', name_ind: 'Politikus', slug: 'politician' },
  { name_eng: 'Postman', name_ind: 'Tukang Pos', slug: 'postman' },
  { name_eng: 'Professor', name_ind: 'Profesor', slug: 'professor' },
  { name_eng: 'Programmer', name_ind: 'Programer', slug: 'programmer' },
  { name_eng: 'Receptionist', name_ind: 'Resepsionis', slug: 'receptionist' },
  { name_eng: 'Scientist', name_ind: 'Ilmuwan', slug: 'scientist' },
  { name_eng: 'Secretary', name_ind: 'Sekretaris', slug: 'secretary' },
  { name_eng: 'Singer', name_ind: 'Penyanyi', slug: 'singer' },
  { name_eng: 'Soldier', name_ind: 'Tentara', slug: 'soldier' },
  { name_eng: 'Surgeon', name_ind: 'Ahli Bedah', slug: 'surgeon' },
  { name_eng: 'Tailor', name_ind: 'Penjahit', slug: 'tailor' },
  { name_eng: 'Teacher', name_ind: 'Guru', slug: 'teacher' },
  { name_eng: 'Technician', name_ind: 'Teknisi', slug: 'technician' },
  { name_eng: 'Translator', name_ind: 'Penerjemah', slug: 'translator' },
  { name_eng: 'Veterinarian', name_ind: 'Dokter Hewan', slug: 'veterinarian' },
  { name_eng: 'Waiter', name_ind: 'Pelayan Pria', slug: 'waiter' },
  { name_eng: 'Waitress', name_ind: 'Pelayan Wanita', slug: 'waitress' },
  { name_eng: 'Writer', name_ind: 'Penulis', slug: 'writer' },
];

const CATEGORIES = [
  { name_eng: 'Motivational', name_ind: 'Motivasi', slug: 'motivational' },
  { name_eng: 'Inspirational', name_ind: 'Inspirasi', slug: 'inspirational' },
  { name_eng: 'Love', name_ind: 'Cinta', slug: 'love' },
  { name_eng: 'Friendship', name_ind: 'Persahabatan', slug: 'friendship' },
  { name_eng: 'Life', name_ind: 'Kehidupan', slug: 'life' },
  { name_eng: 'Happiness', name_ind: 'Kebahagiaan', slug: 'happiness' },
  { name_eng: 'Wisdom', name_ind: 'Kebijaksanaan', slug: 'wisdom' },
  { name_eng: 'Success', name_ind: 'Kesuksesan', slug: 'success' },
  { name_eng: 'Funny', name_ind: 'Lucu', slug: 'funny' },
  { name_eng: 'Philosophical', name_ind: 'Filsafat', slug: 'philosophical' },
  { name_eng: 'Positive', name_ind: 'Positif', slug: 'positive' },
  { name_eng: 'Sad', name_ind: 'Sedih', slug: 'sad' },
  { name_eng: 'Courage', name_ind: 'Keberanian', slug: 'courage' },
  { name_eng: 'Dream', name_ind: 'Mimpi', slug: 'dream' },
  { name_eng: 'Education', name_ind: 'Pendidikan', slug: 'education' },
  { name_eng: 'Family', name_ind: 'Keluarga', slug: 'family' },
  { name_eng: 'Health', name_ind: 'Kesehatan', slug: 'health' },
  { name_eng: 'Humor', name_ind: 'Humor', slug: 'humor' },
  { name_eng: 'Leadership', name_ind: 'Kepemimpinan', slug: 'leadership' },
  { name_eng: 'Patience', name_ind: 'Kesabaran', slug: 'patience' },
  { name_eng: 'Peace', name_ind: 'Perdamaian', slug: 'peace' },
  { name_eng: 'Spiritual', name_ind: 'Spiritual', slug: 'spiritual' },
  { name_eng: 'Strength', name_ind: 'Kekuatan', slug: 'strength' },
  { name_eng: 'Time', name_ind: 'Waktu', slug: 'time' },
  { name_eng: 'Travel', name_ind: 'Perjalanan', slug: 'travel' },
  { name_eng: 'Work', name_ind: 'Kerja', slug: 'work' },
  { name_eng: 'Art', name_ind: 'Seni', slug: 'art' },
  { name_eng: 'Nature', name_ind: 'Alam', slug: 'nature' },
  { name_eng: 'Freedom', name_ind: 'Kebebasan', slug: 'freedom' },
  { name_eng: 'Gratitude', name_ind: 'Rasa Syukur', slug: 'gratitude' },
  { name_eng: 'Forgiveness', name_ind: 'Pengampunan', slug: 'forgiveness' },
  { name_eng: 'Self-love', name_ind: 'Cinta Diri', slug: 'self-love' },
  { name_eng: 'Mindfulness', name_ind: 'Kewaspadaan', slug: 'mindfulness' },
  { name_eng: 'Adventure', name_ind: 'Petualangan', slug: 'adventure' },
  { name_eng: 'Hope', name_ind: 'Harapan', slug: 'hope' },
  { name_eng: 'Change', name_ind: 'Perubahan', slug: 'change' },
  { name_eng: 'Determination', name_ind: 'Tekad', slug: 'determination' },
  { name_eng: 'Resilience', name_ind: 'Ketahanan', slug: 'resilience' },
  { name_eng: 'Empathy', name_ind: 'Empati', slug: 'empathy' },
  { name_eng: 'Compassion', name_ind: 'Belas Kasihan', slug: 'compassion' },
  { name_eng: 'Kindness', name_ind: 'Kebaikan', slug: 'kindness' },
  { name_eng: 'Faith', name_ind: 'Iman', slug: 'faith' },
];

const prisma = new PrismaClient();
async function main() {
  await prisma.nationality.createMany({
    data: NATIONALITIES,
  });

  await prisma.profession.createMany({
    data: PROFESSIONS,
  });

  await prisma.category.createMany({
    data: CATEGORIES,
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
